### ISSUE TITLE
Add support for build information

### ISSUE THREAD

**Issue by josephearl** [matt-usurp/validate-semver#10]
Build can appear with on it's own or combination with a pre-release. Examples: 1.0.0-alpha+001, 1.0.0+20130313144700, 1.0.0-beta+exp.sha.5114f85, 1.0.0+21AF26D3----117B344092BD.

This should be present in a new build output of the action

**Comment by matt-usurp** [comment]
Yeah this is in the specification so I think it would be good 👍🏻 

https://semver.org/#spec-item-10
