### ISSUE TITLE
Empty pre-release `v1-` results in malformed version `1.0.0-`

### ISSUE THREAD

**Issue by josephearl** [matt-usurp/validate-semver#11]
Currently this action will parse a malformed pre-release, e.g. `v1-` as version `1.0.0-` with an empty extra.

I think this should either be invalid, or coerce to a version of `1.0.0`.

**Comment by matt-usurp** [comment]
Fix available in https://github.com/matt-usurp/validate-semver/releases/tag/v2.1.0 and on the `v2` branch
